bump the mininal version of rust to allow the windows release
otherwise, fails with:
  Downloaded xattr v1.6.1
error: rustc 1.87.0 is not supported by the following package:
  sysinfo@0.37.2 requires rustc 1.88
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.87.0

  × failed to find bin sed (path+file:///D:/a/sed/sed#0.0.1) -- did the cargo build above have errors?